#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::ByteStream;
use utf8;

my $estados = [{sigla => 'ES', nome => 'Espírito Santo'}, 
							 {sigla => 'MG', nome => 'Minas Gerais'}, 
							 {sigla => 'RJ', nome => 'Rio de Janeiro'}, 
							 {sigla => 'SP', nome => 'São Paulo'}];

my $cidades = [{id => 1, estado => 'SP', nome => 'São Bernardo'},
							 {id => 2, estado => 'SP', nome => 'São Caetano'},
							 {id => 3, estado => 'SP', nome => 'Ribeirão Pires'},
							 {id => 4, estado => 'SP', nome => 'São Paulo'},
							 {id => 5, estado => 'SP', nome => 'Diadema'},
							 {id => 6, estado => 'SP', nome => 'Osasco'},
							 {id => 7, estado => 'MG', nome => 'Belo Horizonte'},
							 {id => 8, estado => 'MG', nome => 'Santa Luzia'},
							 {id => 9, estado => 'MG', nome => 'Betim'},
							 {id => 10, estado => 'MG', nome => 'Contagem'}];
							 
# Documentation browser under "/perldoc"
plugin 'PODRenderer';

helper menu_ativo => sub {
	my ($self, $menu) = @_;
	return ($self->stash('menu') eq $menu) ? Mojo::ByteStream->new(' class="active"') : '';
};

helper redirect_erro => sub {
	my ($self, $caminho, $mensagem) = @_;
	$self->tx->req->method('GET');
	$self->tx->req->url->path($caminho);
	$self->app->defaults(mensagem_erro => $mensagem);
	$self->app->handler($self->tx);
	$self->app->defaults(mensagem_erro => '');	
	$self->rendered;
};

helper redirect_sucesso => sub {
	my ($self, $caminho, $mensagem) = @_;
	$self->tx->req->method('GET');
	$self->tx->req->url->path($caminho);
	$self->app->defaults(mensagem_sucesso => $mensagem);
	$self->app->handler($self->tx);
	$self->app->defaults(mensagem_sucesso => '');	
	$self->rendered;
};

get '/' => sub {
	my $self = shift;
	$self->render('index');
};

get '/estado' => sub {
	my $self = shift;
	$self->render('estado/listar', dados => $estados);
};

any ['get', 'post'] => '/estado/editar/:sigla' => {sigla => undef} => sub {
	my $self = shift;
	my $acao = undef;
	my $estado = undef;
	if ($self->req->method eq 'GET') {
		my $sigla = $self->param('sigla');

		if (defined($sigla)) {
			for (@$estados) {
				if ($_->{sigla} eq $sigla) {
					$estado = $_;
					$acao = 'A';
					last;
				}
			}
		} else {
			$estado = {sigla => '', nome => ''};
			$acao = 'I';
		}

		if (defined($estado)) {
			$self->render('estado/editar', 
				dados => $estado, 
				acao => $acao);
		} else {
			$self->redirect_erro('/estado', "Estado não encontrado para a sigla '$sigla'.");
		}
	} else { # POST
		$acao = uc($self->req->param('acao'));
		$estado = {sigla => uc($self->req->param('sigla')), 
			nome => $self->req->param('nome')}; 
		my $mensagem = undef;

		unless ($mensagem || $estado->{sigla} =~ /^[A-Z]{2}$/) {
			 $mensagem = 'Informe a sigla do estado';
		}

		unless ($mensagem || $estado->{nome} =~ /^\w{2}/) {
			 $mensagem = 'Informe o nome do estado';
		}

		unless ($mensagem || $acao =~ /^[AI]$/) {
			 $mensagem = 'Ação inválida';
		}
		
		# todo: ja existe estado com a sigla
		if (!defined($mensagem) && $acao eq 'I' && $estado->{sigla} eq 'SP') {
			 $mensagem = 'Estado já cadastrado';
		}

		if ($mensagem) {
			$self->render('estado/editar', 
				dados => $estado, 
				acao => $acao,
				mensagem_erro => $mensagem);
		} else {
			if ($acao eq 'I') {
				$self->redirect_sucesso('/estado', 'Registro incluído com sucesso.');
			} else {
				$self->redirect_sucesso('/estado', 'Registro atualizado com sucesso.');
			}
		}
	}
};

get '/estado/excluir/:sigla' => sub {
	my $self = shift;
	my $sigla = $self->param('sigla');
	if ($sigla eq 'SP') {
		$self->redirect_erro("/estado", "Não é possível excluir o estado '$sigla' porque existem cidades cadastradas.");
	} else {
		$self->redirect_sucesso('/estado', 'Registro excluído com sucesso.');
	}
};

any ['get', 'post'] => '/cidade' => sub {
	my $self = shift;
	if ($self->req->method eq 'GET') {
		$self->render('cidade/listar', dados => []);
	} else {
		my $pesquisa = $self->req->param('pesquisa');
		my $fitrado = [];
		if ($pesquisa) {
			$fitrado = [grep {$_->{nome} =~ /$pesquisa/i} @$cidades];
		}
		$self->render('cidade/listar', 
			dados => $fitrado, 
			mensagem_erro => (@$fitrado ? undef : 'Nenhuma cidade encontrada para o critério'));
	}
};

# => [id => qr/\d+/]
any ['get', 'post'] => '/cidade/editar/:id' => {id => undef} => sub {
	my $self = shift;
	my $acao = undef;
	my $cidade = undef;
	if ($self->req->method eq 'GET') {
		my $id = $self->param('id');

		if (defined($id)) {
			for (@$cidades) {
				if ($_->{id} eq $id) {
					$cidade = $_;
					$acao = 'A';
					last;
				}
			}
		} else {
			$cidade = {id => '', estado => '', nome => ''};
			$acao = 'I';
		}

		if (defined($cidade)) {
			$self->render('cidade/editar', 
				estados => $estados, 
				dados => $cidade, 
				acao => $acao);
		} else {
			$self->redirect_erro('/cidade', 'Cidade não encontrada.');
		}
	} else { # POST
		$acao = uc($self->req->param('acao'));
		$cidade = {id => $self->req->param('id'), 
			estado => uc($self->req->param('estado')), 
			nome => $self->req->param('nome')}; 
		my $mensagem = undef;

		if (!defined($mensagem) && $acao eq 'A' && $cidade->{id} !~ /^\d+$/) {
			 $mensagem = 'Id inválido';
		}

		unless ($mensagem || $cidade->{estado} =~ /^[A-Z]{2}$/) {
			 $mensagem = 'Selecione o estado';
		}

		unless ($mensagem || $cidade->{nome} =~ /^\w{2}/) {
			 $mensagem = 'Informe o nome da cidade';
		}

		unless ($mensagem || $acao =~ /^[AI]$/) {
			 $mensagem = 'Ação inválida';
		}
		
		# todo: ja existe cidade com o mesmo nome no estado
		if (!defined($mensagem) && $acao eq 'I' && $cidade->{estado} eq 'RJ') {
			 $mensagem = 'Já existe uma cidade com o mesmo nome este estado.';
		}

		if ($mensagem) {
			$self->render('cidade/editar', 
				estados => $estados, 
				dados => $cidade, 
				acao => $acao,
				mensagem_erro => $mensagem);
		} else {
			if ($acao eq 'I') {
				$self->redirect_sucesso('/cidade', 'Registro incluído com sucesso.');
			} else {
				$self->redirect_sucesso('/cidade', 'Registro atualizado com sucesso.');
			}
		}
	}
};	
		
app->defaults(layout => 'default');
app->defaults(mensagem_erro => '');
app->defaults(mensagem_sucesso => '');
app->secret('sao seus olhos');
app->start;
__DATA__

@@ layouts/default.html.ep
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Sistema de Teste</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Le styles -->
		<link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css" rel="stylesheet">
		<style>
			body {
				padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
			}
			
			td.botoes {
				padding-left: 20px
			}
		</style>

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

	</head>

	<body>

		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href="/">Sistema de Teste</a>
				</div>
			</div>
		</div>		

		<div class="container">

			<div class="row">
				<div class="span2">
					<ul class="nav nav-pills nav-stacked">
						<li<%= menu_ativo 'estado' %>><a href="/estado" data-togglex="tab">Estado</a></li>
						<li<%= menu_ativo 'cidade' %>><a href="/cidade" data-togglex="tab">Cidade</a></li>
					</ul>
				</div>
				<div class="span8">
					% if ($mensagem_erro) {
						<div class="alert alert-error">
							<button class="close" data-dismiss="alert">×</button>
							%= $mensagem_erro
						</div>
					% }
					% if ($mensagem_sucesso) {
						<div class="alert alert-success">
							<button class="close" data-dismiss="alert">×</button>
							%= $mensagem_sucesso
						</div>
					% }					
<%= content %>
				</div>
			</div>

		</div>

		<!-- Le javascript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="http://code.jquery.com/jquery-1.8.0.min.js"></script>
		<script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"></script>

	</body>
</html>

@@ index.html.ep
% stash menu => '';
<h1>Bem-vindo ao sistema de teste</h1>

@@ estado/listar.html.ep
% stash menu => 'estado';
<p>Lista com os estados cadastrados</p>
<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th class="span1"></th>
			<th class="span1">Sigla</th>
			<th class="span6">Nome</th>
		</tr>
	</thead>
	<tbody>
		% for my $estado (@$dados) {
		<tr>
			<td class="botoes"><a href="/estado/editar/<%= $estado->{sigla} %>"><i class="icon-edit"></i></a></td>
			<td><%= $estado->{sigla} %></a></td>
			<td><%= $estado->{nome} %></td>
		</tr>
		% }
	</tbody>
</table>
<a href="/estado/editar" class="btn btn-primary">Novo</a>

@@ estado/editar.html.ep
% stash menu => 'estado';
% if ($acao eq 'A') {
	<h3>Editar Estado</h3> 
% } else {
	<h3>Novo Estado</h3> 
% }
<form class="form-vertical" method="POST">
	%= hidden_field acao => $acao
	<div class="control-group">
		<label class="control-label" for="sigla">Sigla:</label>
		<div class="controls">
			% if ($acao eq 'A') {
				%= hidden_field sigla => $dados->{sigla}
				<strong><%= $dados->{sigla}%></strong> 
			% } else {
				<input type="text" class="input-mini" id="sigla" name="sigla" value="<%= $dados->{sigla} %>">
			% }
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="nome">Nome: </label>
		<div class="controls">
			<input type="text" class="input-xlarge" id="nome" name="nome" value="<%= $dados->{nome} %>">
		</div>
	</div>
	<div class="form-actions">
		<button type="submit" class="btn btn-primary">Salvar</button>
% if ($acao eq 'A') {
		<a href="/estado/excluir/<%= $dados->{sigla}%>" onclick="$('#myModal').modal('show'); return false;" class="btn btn-danger">Excluir</a>
% }
	</div>	
	<div class="modal hide" id="myModal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Excluir Estado</h3>
		</div>
		<div class="modal-body">
			<p>Confirma a exclusão do estado?</p>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn btn-primary" data-dismiss="modal">Cancelar</a>
			<a href="/estado/excluir/<%= $dados->{sigla}%>" class="btn btn-danger">Excluir</a>
		</div>
	</div>
</form>

@@ cidade/listar.html.ep
% stash menu => 'cidade';
<form class="well form-search" method="POST"	>
	<input type="text" class="input-medium search-query" id="pesquisa" name="pesquisa" value="<%= param('pesquisa') %>">
	<button type="submit" class="btn">Buscar</button>
</form>
% if (@$dados) {
<p>Lista com as cidades cadastradas</p>
<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th class="span1"></th>
			<th class="span1">Estado</th>
			<th class="span6">Nome</th>
		</tr>
	</thead>
	<tbody>
		% for my $cidade (@$dados) {
		<tr>
			<td class="botoes"><a href="/cidade/editar/<%= $cidade->{id} %>"><i class="icon-edit"></i></a></td>
			<td><%= $cidade->{estado} %></td>
			<td><%= $cidade->{nome} %></td>
		</tr>
		% }
	</tbody>
</table>
% }
<a href="/cidade/editar" class="btn btn-primary">Nova</a>

@@ cidade/editar.html.ep
% stash menu => 'cidade';
% if ($acao eq 'A') {
	<h3>Editar Cidade</h3> 
% } else {
	<h3>Nova Cidade</h3> 
% }
<form class="form-vertical" method="POST">
	%= hidden_field acao => $acao
	%= hidden_field id => $dados->{id}
	<div class="control-group">
		<label class="control-label" for="sigla">Estado:</label>
		<div class="controls">
			<select id="estado" name="estado">
				<option value=""></option>
				% for (@$estados) {
					<option value="<%= $_->{sigla} %>"<%= $_->{sigla} eq $dados->{estado} ? ' selected' : '' %>><%= $_->{nome} %></option>
				% }
			</select>
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="nome">Nome: </label>
		<div class="controls">
			<input type="text" class="input-xlarge" id="nome" name="nome" value="<%= $dados->{nome} %>">
		</div>
	</div>
	<div class="form-actions">
		<button type="submit" class="btn btn-primary">Salvar</button>
% if ($acao eq 'A') {
		<a href="/cidade/excluir/<%= $dados->{id}%>" onclick="$('#myModal').modal('show'); return false;" class="btn btn-danger">Excluir</a>
% }
	</div>	
	<div class="modal hide" id="myModal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Excluir Cidade</h3>
		</div>
		<div class="modal-body">
			<p>Confirma a exclusão da cidade?</p>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn btn-primary" data-dismiss="modal">Cancelar</a>
			<a href="/cidade/excluir/<%= $dados->{id}%>" class="btn btn-danger">Excluir</a>
		</div>
	</div>
</form>
